version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.17.8
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.17.8
    ports:
      - "5601:5601"

